= Demonstrate bugs

This project was initially build to test native processor applications.
I discover a problem with `@ServiceConnection` and the recommended use of `@ConfigurationProperties` for Kotlin

== Scripts

* `build-test.sh` will build Java and Kotlin version and execute tests. Expect failure in `com.example.testprocessor.testcontainers.TestProcessorServiceConnectionTests`
* `build-fail.sh` will build Java and Kotlin version and execute tests Expect many failures
* `build-images.sh` will build container images for both versions
* `inspect-images.sh` will extract the configuration json label and check for presence of expected properties.

== Running Tests

[source,shell]
----
cd java
./gradlew test -Ptag=test                 <1>
./gradlew test -Ptag=integration          <2>
./gradlew test -Ptag=integration -Pfork=1 <3>
./gradlew test                            <4>
./gradlew test -Pfork=0                   <5>

cd ../kotlin
./gradlew test -Ptag=test                 <6>
./gradlew test -Ptag=integration          <7>
./gradlew test                            <8>
./gradlew test -Pfork=0                   <9>
----

<1> Java - execute `MockBinderTest` only
<2> Java - execute all tests in `com.example.testprocessor.testcontainers`
<3> Java - execute all tests in `com.example.testprocessor.testcontainers`, but use new JVM for each test
<4> Java - execute all tests with forkEvery 1
<5> Java - execute all tests with forkEvery 0
<6> Kotlin - execute `MockBinderTest` only
<7> Kotlin - execute all tests in `com.example.testprocessor.testcontainers`
<8> Kotlin - execute all tests, but use new JVM for each test
<9> Kotlin - execute all tests with forkEvery 0

== Conclusions
The expectation from `@ConfigurationProperties` is to produce a JSON file
[source,json]
....
{
  "groups": [
    {
      "name": "com.example.testprocessor",
      "type": "com.example.testprocessor.TestConfiguration",
      "sourceType": "com.example.testprocessor.TestConfiguration"
    }
  ],
  "properties": [
    {
      "name": "com.example.testprocessor.addition",
      "type": "java.lang.String",
      "description": "Will be added to name to make fullName",
      "sourceType": "com.example.testprocessor.TestConfiguration"
    }
  ],
  "hints": []
}
....

To create Kotlin `@ConfigurationProperties` annotated classes to work properly the recommended definition is incorrect.

=== Recommendation
[source,kotlin]
....
@ConfigurationProperties2(prefix = "com.example.testprocessor2")
data class TestConfiguration(
    /**
     * Will be added to name to make fullName
     */
    val addition: String = "N/A"
)
....

=== Working version
[source,kotlin]
....
@ConfigurationProperties(prefix = "com.example.testprocessor")
class TestConfiguration {
    /**
     * Will be added to name to make fullName
     */
    var addition: String = "N/A"
}
....

Produced org.springframework.cloud.dataflow.spring-configuration-metadata.json
[source,json]
....
{
  "groups": [
    { "name": "com.example.testprocessor", "type": "com.example.testprocessor.TestConfiguration", "sourceType": "com.example.testprocessor.TestConfiguration" },
    { "name": "com.example.testprocessor2", "type": "com.example.testprocessor.TestConfiguration2", "sourceType": "com.example.testprocessor.TestConfiguration2" }
  ],
  "properties": [
    {
      "name": "com.example.testprocessor.addition",
      "type": "java.lang.String",
      "description": "Will be added to name to make fullName",
      "sourceType": "com.example.testprocessor.TestConfiguration"
    }
  ]
}
....
== SCDF Configuration

Build the container

[source,shell]
----
./gradlew bootBuildImage -PuseNative=true
----

From data flow installation script https://github.com/spring-cloud/spring-cloud-dataflow/releases/download/v2.11.4/spring-cloud-dataflow-package-2.11.4.zip[package]

This will load the local docker container into the configured k8s registry.

_The image may not load in kind or minikube if there is a pod running that was created with the image._

[source,shell]
----
source ./deploy/k8s/export-dataflow-ip.sh
./deploy/k8s/load-image.sh "test-processor-kotlin:latest" true
----

Register application and deploy stream.

[source,shell]
----
export SCDF_SHELL=<location of ./deploy/shell>
./register-app-create-dsl.sh
----