= Getting Started

== Running Tests

[source,shell]
----
cd java
./gradlew test -Ptag=test                 <1>
./gradlew test -Ptag=integration          <2>
./gradlew test -Ptag=integration -Pfork=1 <3>
./gradlew test                            <4>
./gradlew test -Pfork=1                   <5>

cd ../kotlin
./gradlew test -Ptag=test                 <6>
./gradlew test -Ptag=integration          <7>
./gradlew test                            <8>
./gradlew test -Pfork=1                   <9>
----

<1> Java - execute `MockBinderTest` only
<2> Java - execute all tests in `com.example.testprocessor.testcontainers`
<3> Java - execute all tests in `com.example.testprocessor.testcontainers`, but use new JVM for each test
<4> Java - execute all tests
<5> Java - execute all tests, but use new JVM for each test
<6> Kotlin - execute `MockBinderTest` only
<7> Kotlin - execute all tests in `com.example.testprocessor.testcontainers`
<8> Kotlin - execute all tests
<9> Kotlin - execute all tests, but use new JVM for each test


== Reference Documentation

For further reference, please consider the following sections:

* https://docs.gradle.org[Official Gradle documentation]
* https://docs.spring.io/spring-boot/3.3.3/gradle-plugin[Spring Boot Gradle Plugin Reference Guide]
* https://docs.spring.io/spring-boot/3.3.3/gradle-plugin/packaging-oci-image.html[Create an OCI image]
* https://docs.spring.io/spring-boot/3.3.3/reference/packaging/native-image/introducing-graalvm-native-images.html[GraalVM Native Image Support]
* https://docs.spring.io/spring-boot/3.3.3/reference/testing/testcontainers.html#testing.testcontainers[Spring Boot Testcontainers support]
* https://java.testcontainers.org/modules/kafka/[Testcontainers Kafka Modules Reference Guide]
* https://docs.spring.io/spring-boot/docs/3.3.3/reference/htmlsingle/index.html#actuator[Spring Boot Actuator]
* https://docs.spring.io/spring-cloud-function/docs/current/reference/html/spring-cloud-function.html[Function]
* https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#spring-cloud-stream-overview-introducing[Cloud Stream]
* https://docs.spring.io/spring-boot/docs/3.3.3/reference/htmlsingle/index.html#appendix.configuration-metadata.annotation-processor[Spring Configuration Processor]
* https://docs.spring.io/spring-boot/docs/3.3.3/reference/htmlsingle/index.html#messaging.kafka[Spring for Apache Kafka]
* https://docs.spring.io/spring-boot/docs/3.3.3/reference/htmlsingle/index.html#actuator.metrics.export.prometheus[Prometheus]
* https://java.testcontainers.org/[Testcontainers]

== Guides

The following guides illustrate how to use some features concretely:

* https://spring.io/guides/gs/actuator-service/[Building a RESTful Web Service with Spring Boot Actuator]

== Additional Links

These additional references should also help you:

* https://scans.gradle.com#gradle[Gradle Build Scans – insights for your project's build]
* https://docs.spring.io/spring-boot/3.3.3/how-to/aot.html[Configure AOT settings in Build Plugin]
* https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples[Various sample apps using Spring Cloud Function]

== GraalVM Native Support

This project has been configured to let you generate either a lightweight container or a native executable.
It is also possible to run your tests in a native image.

The useNative properties in `gradle.properties` can be changed permanently or invoked as follows:

[source,shell]
----
./gradlew bootBuildImage -PuseNative=true
----

=== Lightweight Container with Cloud Native Buildpacks

If you're already familiar with Spring Boot container images support, this is the easiest way to get started.
Docker should be installed and configured on your machine prior to creating the image.

To create the image, run the following goal:

[source,shell]
----
./gradlew bootBuildImage
----

=== Executable with Native Build Tools

Use this option if you want to explore more options such as running your tests in a native image.
The GraalVM `native-image` compiler should be installed and configured on your machine.

NOTE: GraalVM 22.3+ is required.

To create the executable, run the following goal:

----
$ ./gradlew nativeCompile
----

Then, you can run the app as follows:

----
$ build/native/nativeCompile/test-processor
----

You can also run your existing tests suite in a native image.
This is an efficient way to validate the compatibility of your application.

To run your existing tests in a native image, run the following goal:

----
$ ./gradlew nativeTest
----

=== Gradle Toolchain support

There are some limitations regarding Native Build Tools and Gradle toolchains.
Native Build Tools disable toolchain support by default.
Effectively, native image compilation is done with the JDK used to execute Gradle.
You can read more about https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#configuration-toolchains[toolchain support in the Native Build Tools here].

=== Testcontainers support

This project uses https://docs.spring.io/spring-boot/3.3.3/reference/features/dev-services.html#features.dev-services.testcontainers[Testcontainers at development time].

Testcontainers has been configured to use the following Docker images:

* https://hub.docker.com/r/confluentinc/cp-kafka[`confluentinc/cp-kafka:latest`]

Please review the tags of the used images and set them to the same as you're running in production.

== SCDF Configuration

Build the container

[source,shell]
----
./gradlew bootBuildImage -PuseNative=true
----

From data flow installation script https://github.com/spring-cloud/spring-cloud-dataflow/releases/download/v2.11.4/spring-cloud-dataflow-package-2.11.4.zip[package]

This will load the local docker container into the configured k8s registry.

_The image may not load in kind or minikube if there is a pod running that was created with the image._

[source,shell]
----
source ./deploy/k8s/export-dataflow-ip.sh
./deploy/k8s/load-image.sh "example.com/library/test-processor:latest" true
----

Register application and deploy stream.

[source,shell]
----
export SCDF_SHELL=<location of ./deploy/shell>
./register-app-create-dsl.sh
----